version: '2.4'
services:
    pytorch_jupyter:
        image: acebee007/pytorch:latest
        runtime: nvidia
        ports:
            - "8888:8888"
        volumes:
            - ~/workspace/project_workspace/root:/root
            - ~/workspace/project_workspace/tf:/workspace
            - ~/workspace/project_workspace/tblog:/tblog
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        command: jupyter-notebook --ip=0.0.0.0 --allow-root --notebook-dir=/workspace
        restart: unless-stopped
    pytorch_tensorboard:
        image: acebee007/pytorch:latest
        runtime: nvidia
        ports:
            - "6006:6006"
        links:
            - pytorch_jupyter
        volumes:
            - ~/workspace/project_workspace/tblog:/tblog
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        command: tensorboard --host=0.0.0.0 --port=6006 --logdir=/tblog
        restart: unless-stopped

