version: "3"

services:
  traefik:
    image: traefik:v2.7
    networks:
      - traefik-network
    deploy:
      placement:
        constraints:
          - "node.labels.traefikserver==true"
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock


networks:
  traefik-network:
    external: true

