icecast:
  image: docker-icecast_icecast:latest
    #build: .
  volumes:
    - logs:/var/log/icecast2
    - /etc/localtime:/etc/localtime:ro
    - ./etc/icecast2:/etc/icecast2
  environment:
    - ICECAST_SOURCE_PASSWORD=hackme
    - ICECAST_ADMIN_PASSWORD=hackme
    - ICECAST_PASSWORD=hackme
    - ICECAST_RELAY_PASSWORD=hackme
  restart: unless-stopped
  ports:
    - "8001:8000"

mpd:
  image: vimagick_arm/mpd:latest
  ports:
    - "6601:6600"
    - "8801:8800"
  volumes:
    - ./data/mpd/config/mpd.conf:/etc/mpd.conf
    - /mnt/SG_500G/Musics/AnimeSong:/var/lib/mpd/music
    - ./data/mpd/playlists:/var/lib/mpd/playlists
  devices:
    - /dev/snd
  restart: unless-stopped
  links:
    - icecast

mpd2:
  image: vimagick_arm/mpd:latest
  ports:
    - "6602:6600"
    - "8802:8800"
  volumes:
    - ./data/mpd2/config/mpd.conf:/etc/mpd.conf
    - /mnt/SG_500G/Musics/EnglishSongs:/var/lib/mpd/music
    - ./data/mpd2/playlists:/var/lib/mpd/playlists
  devices:
    - /dev/snd
  restart: unless-stopped
  links:
    - icecast

mpd3:
  image: vimagick_arm/mpd:latest
  ports:
    - "6603:6600"
    - "8803:8800"
  volumes:
    - ./data/mpd3/config/mpd.conf:/etc/mpd.conf
    - /mnt/SG_500G/Musics/classicMusic:/var/lib/mpd/music
    - ./data/mpd3/playlists:/var/lib/mpd/playlists
  devices:
    - /dev/snd
  restart: unless-stopped
  links:
    - icecast
