version: "3"

x-env: &env
  image: mylocal/debian-mpd:latest
  networks:
    - icecast-network
  environment:
    - TZ=Europe/London
    - UMASK_SET=022 #optional
    - MYMPD_SSL=false
      #restart: always
  deploy:
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 10
      window: 120s

networks:
  icecast-network:
    external: true


