version: "3"

x-env: &env
  image: mylocal/debian-mpd:latest
  networks:
    - icecast-network
  environment:
    - TZ=Europe/London
    - UMASK_SET=022 #optional
    - MYMPD_SSL=false
      #restart: always
  deploy:
    placement:
      constraints:
        - "node.hostname==ubuntu-raspi4"
    restart_policy:
      condition: any
      delay: 15s
      window: 120s

networks:
  icecast-network:
    external: true


